name: Build

on:
  push:
    branches:
      -"main"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install dependencies
        run: npm install
      - name: start application
        run: npm start