name: First React Application

on:
  push:
    branches:
      -"main"

jobs:
  build:
    runs-on: ubuntu-latest

strategy:
  matrix:
    node-version: [15.x]

steps:
  -uses: actions/checkout@v1

  -name: install dependencies
    run: npm install
  -name: run build
    run: npm start
  -name: run tests
    run: npm test